
spdlog: libs/spdlog/build/libspdlog.a

libs/spdlog/build:
	mkdir -p libs/spdlog/build

libs/spdlog/build/libspdlog.a: libs/spdlog/build
	cd libs/spdlog/build; cmake ..; make

raylib: libs/raylib/src/libraylib.a

libs/raylib/src/libraylib.a:
	cd libs/raylib/src; make PLATFORM=PLATFORM_DESKTOP


libs: spdlog raylib
